"""insert collection function

Revision ID: 380025eebc85
Revises: c7cf1181a206
Create Date: 2017-11-05 01:11:14.309821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380025eebc85'
down_revision = 'c7cf1181a206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections')
    # ### end Alembic commands ###
