"""table Label add column type

Revision ID: c7cf1181a206
Revises: ed117c4918a6
Create Date: 2017-11-04 13:39:34.260169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cf1181a206'
down_revision = 'ed117c4918a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('type', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labels', 'type')
    # ### end Alembic commands ###
